updates

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -33,6 +33,20 @@ echo "-------> Done installing forge"
 #dpkg -x $CACHE_DIR/forge.deb $BUILD_DIR/vendor/forge
 
 
-echo "-------> Done running foundryup"
+FOUNDRYUP_PATH=$(find /app -name foundryup 2>/dev/null)
+
+# Check if foundryup is available
+if [ -z "$FOUNDRYUP_PATH" ]; then
+    echo "-------> Error: foundryup command not found after installation!"
+    exit 1
+fi
+
+echo "-------> Running foundryup using path: $FOUNDRYUP_PATH"
+$FOUNDRYUP_PATH
+
+echo "-------> Done with forge buildpack"
+Note that using find will search for foundryup starting at the /app
+
+
 
 #echo "export PATH=\$HOME/vendor/forge/usr/bin:\$PATH" >> $BUILD_DIR/.profile.d/whois_buildpack_paths.sh
