foundryup

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -33,5 +33,16 @@ echo "---> run foundryup"
 
 export PATH="/app/.foundry/bin:$PATH"
 
+FOUNDRYUP_PATH=$(find /app -name foundryup 2>/dev/null)
+
+# Check if foundryup is available
+if [ -z "$FOUNDRYUP_PATH" ]; then
+    echo "-------> Error: foundryup command not found after installation!"
+    exit 1
+fi
+
+echo "-------> Running foundryup using path: $FOUNDRYUP_PATH"
+$FOUNDRYUP_PATH
+
 
 #echo "export PATH=\$HOME/vendor/forge/usr/bin:\$PATH" >> $BUILD_DIR/.profile.d/whois_buildpack_paths.sh
